version: '3.9'
services:
  app:
    env_file: ./docker/app/.env
    build:
      context: .
      tags:
      - "cr1pper/rest-service:nestjs-app"
      dockerfile: ${APP_DOCKERFILE}
    networks:
      users-bridge:
        ipv4_address: ${NETWORK_APP_IP}
    secrets:
      - source: privkey
        target: ${SSH_PRIVKEY}
      - source: cert
        target: ${SSH_CERT}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PORT: ${PORT}
      APP_WORKDIR: ${APP_WORKDIR}
      APP_CMD: ${APP_CMD}
      POSTGRES_HOST: ${NETWORK_BASE_IP}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SSH_PRIVKEY: /run/secrets/${SSH_PRIVKEY}
      SSH_CERT: /run/secrets/${SSH_CERT}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS}
    volumes:
      - ${APP_VOLUME}/node_modules:${APP_WORKDIR}/node_modules
      - ${APP_VOLUME}/src:${APP_WORKDIR}/src
      - ${APP_VOLUME}/doc:${APP_WORKDIR}/doc
    ports:
      - ${PORT}:${PORT}
      - ${DOC_PORT}:${DOC_PORT}
    restart: unless-stopped
  postgres:
    build: 
      dockerfile: ${BASE_DOCKERFILE}
      tags:
      - "cr1pper/rest-service:postgres-db"
    command:
      - "postgres"
      - "-c"
      - "logging_collector=on"
    networks:
      users-bridge:
        ipv4_address: ${NETWORK_BASE_IP}
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata" # postgres official image constant
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
networks:
  users-bridge:
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
secrets:
  privkey:
    file: ${SSH_PRIVKEY} 
  cert:
    file: ${SSH_CERT} 
