version: '3.9'
name: nodejs-rest-service
services:
  app:
    container_name: app
    build:
      context: .
      tags:
        - "${REPOSITORY}:nestjs-app"
      dockerfile: ${APP_DOCKERFILE}
      args:
        APP_WORKDIR: ${APP_WORKDIR}
        PORT: ${PORT}
    networks:
      users-bridge:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PORT: ${PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SSH_PRIVKEY: ${SSH_PRIVKEY}
      SSH_CERT: ${SSH_CERT}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS}
      LOG_LVL: ${LOG_LVL}
      LOG_SIZE: ${LOG_SIZE}
      LOG_PATH: ${LOG_PATH}
      TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
      TOKEN_REFRESH_EXPIRE_TIME: ${TOKEN_REFRESH_EXPIRE_TIME}
    volumes:
      - ${APP_VOLUME}/src:${APP_WORKDIR}/src
      - ${APP_VOLUME}/logs:${APP_WORKDIR}/logs
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
  postgres:
    container_name: postgres
    build:
      dockerfile: ${BASE_DOCKERFILE}
      tags:
        - "${REPOSITORY}:postgres-db"
    command:
      - "postgres"
      - "-c"
      - "logging_collector=on"
    networks:
      users-bridge:
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
networks:
  users-bridge:
    driver: bridge
volumes:
  pg_data:
