version: '3'
services:
  postgres:
    build: ./base/
    environment:
      POSTGRES_DB: "pgbase"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../base/Init Database:/docker-entrypoint-initdb.d
      - ../base:/var/lib/postgresql/data
    ports:
      - "5432:5432"